name: genesis-gpu
channels:
  - conda-forge
dependencies:
  - python=3.11.14
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu130
      - torch==2.9.0+cu130
      - torchvision==0.24.0+cu130
      - genesis-world==1.4.1
      - rsl-rl-lib==5.5.1
      - numpy>=1.26.4,<2.3
      - PyYAML>=6.0
      - tensorboard>=2.20
      - wandb>=0.22.3
